export const initalStateAuth = {
  accessToken: "",
  setAccessToken: () => null,
  user: {
    address: "",
    avatar: "",
    birthday: "",
    createdAt: "",
    deletedAt: "",
    email: "",
    firstName: "",
    gender: "",
    id: "",
    lastName: "",
    password: "",
    phoneNumber: "",
    updatedAt: "",
  },
  setUser: () => null,
};
